<?
echo "PHP_VERSION: ".PHP_VERSION, "<br>";
echo "PHP_OS: ".PHP_OS, "<br>";
echo "PHP_SAPI : ".PHP_SAPI , "<br>";
echo "PHP_EOL : ".PHP_EOL, "<br>";
echo "PHP_INT_MAX : ".PHP_INT_MAX , "<br>";
echo "PHP_INT_SIZE : ".PHP_INT_SIZE , "<br>";
echo "DEFAULT_INCLUDE_PATH : ".DEFAULT_INCLUDE_PATH , "<br>";
echo "PEAR_INSTALL_DIR : ".PEAR_INSTALL_DIR , "<br>";
echo "PEAR_EXTENSION_DIR : ".PEAR_EXTENSION_DIR , "<br>";
echo "PHP_EXTENSION_DIR : ".PHP_EXTENSION_DIR , "<br>";
echo "PHP_PREFIX : ".PHP_PREFIX , "<br>";
echo "PHP_BINDIR : ".PHP_BINDIR , "<br>";
echo "PHP_LIBDIR : ".PHP_LIBDIR , "<br>";
echo "PHP_DATADIR : ".PHP_DATADIR , "<br>";
echo "PHP_SYSCONFDIR: ".PHP_SYSCONFDIR, "<br>";
echo "PHP_LOCALSTATEDIR : ".PHP_LOCALSTATEDIR , "<br>";
echo "PHP_CONFIG_FILE_PATH : ".PHP_CONFIG_FILE_PATH , "<br>";
echo "PHP_CONFIG_FILE_SCAN_DIR : ".PHP_CONFIG_FILE_SCAN_DIR , "<br>";
echo "PHP_SHLIB_SUFFIX : ".PHP_SHLIB_SUFFIX , "<br>";
//$a = file("2.txt");
//foreach($a as $v){
//	$str = str_replace(PHP_EOL,"",$v);
//	if(strlen($str) > 1)
//	echo "echo '".$str.": '.".$str."."<br>";"."<br>";
//}
echo 'PHP_OUTPUT_HANDLER_START : '.PHP_OUTPUT_HANDLER_START ."<br>";
echo 'PHP_OUTPUT_HANDLER_CONT : '.PHP_OUTPUT_HANDLER_CONT ."<br>";
echo 'PHP_OUTPUT_HANDLER_END : '.PHP_OUTPUT_HANDLER_END ."<br>";
echo 'E_ERROR : '.E_ERROR ."<br>";
echo 'E_WARNING : '.E_WARNING ."<br>";
echo 'E_PARSE : '.E_PARSE ."<br>";
echo 'E_NOTICE : '.E_NOTICE ."<br>";
echo 'E_CORE_ERROR : '.E_CORE_ERROR ."<br>";
echo 'E_CORE_WARNING : '.E_CORE_WARNING ."<br>";
echo 'E_COMPILE_ERROR : '.E_COMPILE_ERROR ."<br>";
echo 'E_COMPILE_WARNING : '.E_COMPILE_WARNING ."<br>";
echo 'E_USER_ERROR : '.E_USER_ERROR ."<br>";
echo 'E_USER_WARNING : '.E_USER_WARNING ."<br>";
echo 'E_USER_NOTICE : '.E_USER_NOTICE ."<br>";
echo 'E_ALL : '.E_ALL ."<br>";
echo 'E_STRICT : '.E_STRICT ."<br>";
echo '__COMPILER_HALT_OFFSET__ : '.__COMPILER_HALT_OFFSET__ ."<br>";
echo 'EXTR_OVERWRITE : '.EXTR_OVERWRITE ."<br>";
echo 'EXTR_SKIP : '.EXTR_SKIP ."<br>";
echo 'EXTR_PREFIX_SAME : '.EXTR_PREFIX_SAME ."<br>";
echo 'EXTR_PREFIX_ALL : '.EXTR_PREFIX_ALL ."<br>";
echo 'EXTR_PREFIX_INVALID : '.EXTR_PREFIX_INVALID ."<br>";
echo 'EXTR_PREFIX_IF_EXISTS : '.EXTR_PREFIX_IF_EXISTS ."<br>";
echo 'EXTR_IF_EXISTS : '.EXTR_IF_EXISTS ."<br>";
echo 'SORT_ASC : '.SORT_ASC ."<br>";
echo 'SORT_DESC : '.SORT_DESC ."<br>";
echo 'SORT_REGULAR : '.SORT_REGULAR ."<br>";
echo 'SORT_NUMERIC : '.SORT_NUMERIC ."<br>";
echo 'SORT_STRING : '.SORT_STRING ."<br>";
echo 'CASE_LOWER : '.CASE_LOWER ."<br>";
echo 'CASE_UPPER : '.CASE_UPPER ."<br>";
echo 'COUNT_NORMAL : '.COUNT_NORMAL ."<br>";
echo 'COUNT_RECURSIVE : '.COUNT_RECURSIVE ."<br>";
echo 'ASSERT_ACTIVE : '.ASSERT_ACTIVE ."<br>";
echo 'ASSERT_CALLBACK : '.ASSERT_CALLBACK ."<br>";
echo 'ASSERT_BAIL : '.ASSERT_BAIL ."<br>";
echo 'ASSERT_WARNING : '.ASSERT_WARNING ."<br>";
echo 'ASSERT_QUIET_EVAL : '.ASSERT_QUIET_EVAL ."<br>";
echo 'CONNECTION_ABORTED : '.CONNECTION_ABORTED ."<br>";
echo 'CONNECTION_NORMAL : '.CONNECTION_NORMAL ."<br>";
echo 'CONNECTION_TIMEOUT : '.CONNECTION_TIMEOUT ."<br>";
echo 'INI_USER : '.INI_USER ."<br>";
echo 'INI_PERDIR : '.INI_PERDIR ."<br>";
echo 'INI_SYSTEM : '.INI_SYSTEM ."<br>";
echo 'INI_ALL : '.INI_ALL ."<br>";
echo 'M_E : '.M_E ."<br>";
echo 'M_LOG2E : '.M_LOG2E ."<br>";
echo 'M_LOG10E : '.M_LOG10E ."<br>";
echo 'M_LN2 : '.M_LN2 ."<br>";
echo 'M_LN10 : '.M_LN10 ."<br>";
echo 'M_PI : '.M_PI ."<br>";
echo 'M_PI_2 : '.M_PI_2 ."<br>";
echo 'M_PI_4 : '.M_PI_4 ."<br>";
echo 'M_1_PI : '.M_1_PI ."<br>";
echo 'M_2_PI : '.M_2_PI ."<br>";
echo 'M_2_SQRTPI : '.M_2_SQRTPI ."<br>";
echo 'M_SQRT2 : '.M_SQRT2 ."<br>";
echo 'M_SQRT1_2 : '.M_SQRT1_2 ."<br>";
echo 'CRYPT_SALT_LENGTH : '.CRYPT_SALT_LENGTH ."<br>";
echo 'CRYPT_STD_DES : '.CRYPT_STD_DES ."<br>";
echo 'CRYPT_EXT_DES : '.CRYPT_EXT_DES ."<br>";
echo 'CRYPT_MD5 : '.CRYPT_MD5 ."<br>";
echo 'CRYPT_BLOWFISH : '.CRYPT_BLOWFISH ."<br>";
echo 'DIRECTORY_SEPARATOR : '.DIRECTORY_SEPARATOR ."<br>";
echo 'SEEK_SET : '.SEEK_SET ."<br>";
echo 'SEEK_CUR : '.SEEK_CUR ."<br>";
echo 'SEEK_END : '.SEEK_END ."<br>";
echo 'LOCK_SH : '.LOCK_SH ."<br>";
echo 'LOCK_EX : '.LOCK_EX ."<br>";
echo 'LOCK_UN : '.LOCK_UN ."<br>";
echo 'LOCK_NB : '.LOCK_NB ."<br>";
echo 'HTML_SPECIALCHARS : '.HTML_SPECIALCHARS ."<br>";
echo 'HTML_ENTITIES : '.HTML_ENTITIES ."<br>";
echo 'ENT_COMPAT : '.ENT_COMPAT ."<br>";
echo 'ENT_QUOTES : '.ENT_QUOTES ."<br>";
echo 'ENT_NOQUOTES : '.ENT_NOQUOTES ."<br>";
echo 'INFO_GENERAL : '.INFO_GENERAL ."<br>";
echo 'INFO_CREDITS : '.INFO_CREDITS ."<br>";
echo 'INFO_CONFIGURATION : '.INFO_CONFIGURATION ."<br>";
echo 'INFO_MODULES : '.INFO_MODULES ."<br>";
echo 'INFO_ENVIRONMENT : '.INFO_ENVIRONMENT ."<br>";
echo 'INFO_VARIABLES : '.INFO_VARIABLES ."<br>";
echo 'INFO_LICENSE : '.INFO_LICENSE ."<br>";
echo 'INFO_ALL : '.INFO_ALL ."<br>";
echo 'CREDITS_GROUP : '.CREDITS_GROUP ."<br>";
echo 'CREDITS_GENERAL : '.CREDITS_GENERAL ."<br>";
echo 'CREDITS_SAPI : '.CREDITS_SAPI ."<br>";
echo 'CREDITS_MODULES : '.CREDITS_MODULES ."<br>";
echo 'CREDITS_DOCS : '.CREDITS_DOCS ."<br>";
echo 'CREDITS_FULLPAGE : '.CREDITS_FULLPAGE ."<br>";
echo 'CREDITS_QA : '.CREDITS_QA ."<br>";
echo 'CREDITS_ALL : '.CREDITS_ALL ."<br>";
echo 'STR_PAD_LEFT : '.STR_PAD_LEFT ."<br>";
echo 'STR_PAD_RIGHT : '.STR_PAD_RIGHT ."<br>";
echo 'STR_PAD_BOTH : '.STR_PAD_BOTH ."<br>";
echo 'PATHINFO_DIRNAME : '.PATHINFO_DIRNAME ."<br>";
echo 'PATHINFO_BASENAME : '.PATHINFO_BASENAME ."<br>";
echo 'PATHINFO_EXTENSION : '.PATHINFO_EXTENSION ."<br>";
echo 'PATH_SEPARATOR : '.PATH_SEPARATOR ."<br>";
echo 'CHAR_MAX : '.CHAR_MAX ."<br>";
echo 'LC_CTYPE : '.LC_CTYPE ."<br>";
echo 'LC_NUMERIC : '.LC_NUMERIC ."<br>";
echo 'LC_TIME : '.LC_TIME ."<br>";
echo 'LC_COLLATE : '.LC_COLLATE ."<br>";
echo 'LC_MONETARY : '.LC_MONETARY ."<br>";
echo 'LC_ALL : '.LC_ALL ."<br>";
echo 'LC_MESSAGES : '.LC_MESSAGES ."<br>";
echo 'ABDAY_1 : '.ABDAY_1 ."<br>";
echo 'ABDAY_2 : '.ABDAY_2 ."<br>";
echo 'ABDAY_3 : '.ABDAY_3 ."<br>";
echo 'ABDAY_4 : '.ABDAY_4 ."<br>";
echo 'ABDAY_5 : '.ABDAY_5 ."<br>";
echo 'ABDAY_6 : '.ABDAY_6 ."<br>";
echo 'ABDAY_7 : '.ABDAY_7 ."<br>";
echo 'DAY_1 : '.DAY_1 ."<br>";
echo 'DAY_2 : '.DAY_2 ."<br>";
echo 'DAY_3 : '.DAY_3 ."<br>";
echo 'DAY_4 : '.DAY_4 ."<br>";
echo 'DAY_5 : '.DAY_5 ."<br>";
echo 'DAY_6 : '.DAY_6 ."<br>";
echo 'DAY_7 : '.DAY_7 ."<br>";
echo 'ABMON_1 : '.ABMON_1 ."<br>";
echo 'ABMON_2 : '.ABMON_2 ."<br>";
echo 'ABMON_3 : '.ABMON_3 ."<br>";
echo 'ABMON_4 : '.ABMON_4 ."<br>";
echo 'ABMON_5 : '.ABMON_5 ."<br>";
echo 'ABMON_6 : '.ABMON_6 ."<br>";
echo 'ABMON_7 : '.ABMON_7 ."<br>";
echo 'ABMON_8 : '.ABMON_8 ."<br>";
echo 'ABMON_9 : '.ABMON_9 ."<br>";
echo 'ABMON_10 : '.ABMON_10 ."<br>";
echo 'ABMON_11 : '.ABMON_11 ."<br>";
echo 'ABMON_12 : '.ABMON_12 ."<br>";
echo 'MON_1 : '.MON_1 ."<br>";
echo 'MON_2 : '.MON_2 ."<br>";
echo 'MON_3 : '.MON_3 ."<br>";
echo 'MON_4 : '.MON_4 ."<br>";
echo 'MON_5 : '.MON_5 ."<br>";
echo 'MON_6 : '.MON_6 ."<br>";
echo 'MON_7 : '.MON_7 ."<br>";
echo 'MON_8 : '.MON_8 ."<br>";
echo 'MON_9 : '.MON_9 ."<br>";
echo 'MON_10 : '.MON_10 ."<br>";
echo 'MON_11 : '.MON_11 ."<br>";
echo 'MON_12 : '.MON_12 ."<br>";
echo 'AM_STR : '.AM_STR ."<br>";
echo 'PM_STR : '.PM_STR ."<br>";
echo 'D_T_FMT : '.D_T_FMT ."<br>";
echo 'D_FMT : '.D_FMT ."<br>";
echo 'T_FMT : '.T_FMT ."<br>";
echo 'T_FMT_AMPM : '.T_FMT_AMPM ."<br>";
echo 'ERA : '.ERA ."<br>";
echo 'ERA_YEAR : '.ERA_YEAR ."<br>";
echo 'ERA_D_T_FMT : '.ERA_D_T_FMT ."<br>";
echo 'ERA_D_FMT : '.ERA_D_FMT ."<br>";
echo 'ERA_T_FMT : '.ERA_T_FMT ."<br>";
echo 'ALT_DIGITS : '.ALT_DIGITS ."<br>";
echo 'INT_CURR_SYMBOL : '.INT_CURR_SYMBOL ."<br>";
echo 'CURRENCY_SYMBOL : '.CURRENCY_SYMBOL ."<br>";
echo 'CRNCYSTR : '.CRNCYSTR ."<br>";
echo 'MON_DECIMAL_POINT : '.MON_DECIMAL_POINT ."<br>";
echo 'MON_THOUSANDS_SEP : '.MON_THOUSANDS_SEP ."<br>";
echo 'MON_GROUPING : '.MON_GROUPING ."<br>";
echo 'POSITIVE_SIGN : '.POSITIVE_SIGN ."<br>";
echo 'NEGATIVE_SIGN : '.NEGATIVE_SIGN ."<br>";
echo 'INT_FRAC_DIGITS : '.INT_FRAC_DIGITS ."<br>";
echo 'FRAC_DIGITS : '.FRAC_DIGITS ."<br>";
echo 'P_CS_PRECEDES : '.P_CS_PRECEDES ."<br>";
echo 'P_SEP_BY_SPACE : '.P_SEP_BY_SPACE ."<br>";
echo 'N_CS_PRECEDES : '.N_CS_PRECEDES ."<br>";
echo 'N_SEP_BY_SPACE : '.N_SEP_BY_SPACE ."<br>";
echo 'P_SIGN_POSN : '.P_SIGN_POSN ."<br>";
echo 'N_SIGN_POSN : '.N_SIGN_POSN ."<br>";
echo 'DECIMAL_POINT : '.DECIMAL_POINT ."<br>";
echo 'RADIXCHAR : '.RADIXCHAR ."<br>";
echo 'THOUSANDS_SEP : '.THOUSANDS_SEP ."<br>";
echo 'THOUSEP : '.THOUSEP ."<br>";
echo 'GROUPING : '.GROUPING ."<br>";
echo 'YESEXPR : '.YESEXPR ."<br>";
echo 'NOEXPR : '.NOEXPR ."<br>";
echo 'YESSTR : '.YESSTR ."<br>";
echo 'NOSTR : '.NOSTR ."<br>";
echo 'CODESET : '.CODESET ."<br>";
echo 'LOG_EMERG : '.LOG_EMERG ."<br>";
echo 'LOG_ALERT : '.LOG_ALERT ."<br>";
echo 'LOG_CRIT : '.LOG_CRIT ."<br>";
echo 'LOG_ERR : '.LOG_ERR ."<br>";
echo 'LOG_WARNING : '.LOG_WARNING ."<br>";
echo 'LOG_NOTICE : '.LOG_NOTICE ."<br>";
echo 'LOG_INFO : '.LOG_INFO ."<br>";
echo 'LOG_DEBUG : '.LOG_DEBUG ."<br>";
echo 'LOG_KERN : '.LOG_KERN ."<br>";
echo 'LOG_USER : '.LOG_USER ."<br>";
echo 'LOG_MAIL : '.LOG_MAIL ."<br>";
echo 'LOG_DAEMON : '.LOG_DAEMON ."<br>";
echo 'LOG_AUTH : '.LOG_AUTH ."<br>";
echo 'LOG_SYSLOG : '.LOG_SYSLOG ."<br>";
echo 'LOG_LPR : '.LOG_LPR ."<br>";
echo 'LOG_NEWS : '.LOG_NEWS ."<br>";
echo 'LOG_UUCP : '.LOG_UUCP ."<br>";
echo 'LOG_CRON : '.LOG_CRON ."<br>";
echo 'LOG_AUTHPRIV : '.LOG_AUTHPRIV ."<br>";
echo 'LOG_LOCAL0 : '.LOG_LOCAL0 ."<br>";
echo 'LOG_LOCAL1 : '.LOG_LOCAL1 ."<br>";
echo 'LOG_LOCAL2 : '.LOG_LOCAL2 ."<br>";
echo 'LOG_LOCAL3 : '.LOG_LOCAL3 ."<br>";
echo 'LOG_LOCAL4 : '.LOG_LOCAL4 ."<br>";
echo 'LOG_LOCAL5 : '.LOG_LOCAL5 ."<br>";
echo 'LOG_LOCAL6 : '.LOG_LOCAL6 ."<br>";
echo 'LOG_LOCAL7 : '.LOG_LOCAL7 ."<br>";
echo 'LOG_PID : '.LOG_PID ."<br>";
echo 'LOG_CONS : '.LOG_CONS ."<br>";
echo 'LOG_ODELAY : '.LOG_ODELAY ."<br>";
echo 'LOG_NDELAY : '.LOG_NDELAY ."<br>";
echo 'LOG_NOWAIT : '.LOG_NOWAIT ."<br>";
echo 'LOG_PERROR : '.LOG_PERROR ."<br>";

?>